sudo: required
services:
  - docker

before_install:
  - docker build -t shoxc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shoxc/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-017694512694"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
